<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="M2B-D-6ZLLXH2" failures="0" tests="6" name="modules.AppEntryFIA" time="0.015" errors="2" timestamp="27 Feb 2018 12:50:38 GMT" skipped="4">
  <testcase classname="modules.AppEntryFIA" name="AuthenticationAndAccessControl" time="0.015">
    <error message="Unresolved compilation problems: 
	XSSFWorkbook cannot be resolved to a type
	XSSFWorkbook cannot be resolved to a type
	XSSFSheet cannot be resolved to a type
	XSSFWorkbook cannot be resolved to a type
" type="java.lang.Error">
      <![CDATA[java.lang.Error: Unresolved compilation problems: XSSFWorkbook cannot be resolved to a typeXSSFWorkbook cannot be resolved to a typeXSSFSheet cannot be resolved to a typeXSSFWorkbook cannot be resolved to a typeat utility.ExcelUtils.setExcelFile(ExcelUtils.java:32)at modules.AppEntryFIA.AuthenticationAndAccessControl(AppEntryFIA.java:46)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.base/java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </error>
  </testcase> <!-- AuthenticationAndAccessControl -->
  <testcase classname="modules.AppEntryFIA" name="LifeInsuranceAndAnnuityPlatform" time="0.000">
    <skipped/>
  </testcase> <!-- LifeInsuranceAndAnnuityPlatform -->
  <testcase classname="modules.AppEntryFIA" name="CLTApplicaionOwnerInformationNewFIA" time="0.000">
    <skipped/>
  </testcase> <!-- CLTApplicaionOwnerInformationNewFIA -->
  <testcase classname="modules.AppEntryFIA" name="ApplicationDefingQuestionnaire" time="0.000">
    <skipped/>
  </testcase> <!-- ApplicationDefingQuestionnaire -->
  <testcase classname="modules.AppEntryFIA" name="AuthenticationAndAccessControl" time="0.000">
    <error message="Unresolved compilation problems: 
	XSSFWorkbook cannot be resolved to a type
	XSSFWorkbook cannot be resolved to a type
	XSSFSheet cannot be resolved to a type
	XSSFWorkbook cannot be resolved to a type
" type="java.lang.Error">
      <![CDATA[java.lang.Error: Unresolved compilation problems: XSSFWorkbook cannot be resolved to a typeXSSFWorkbook cannot be resolved to a typeXSSFSheet cannot be resolved to a typeXSSFWorkbook cannot be resolved to a typeat utility.ExcelUtils.setExcelFile(ExcelUtils.java:32)at modules.AppEntryFIA.AuthenticationAndAccessControl(AppEntryFIA.java:46)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.base/java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:451)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:425)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </error>
  </testcase> <!-- AuthenticationAndAccessControl -->
  <testcase classname="modules.AppEntryFIA" name="AccountWelcome" time="0.000">
    <skipped/>
  </testcase> <!-- AccountWelcome -->
</testsuite> <!-- modules.AppEntryFIA -->
